### ISSUE TITLE
Replace current ticket detail collector with a form

### ISSUE THREAD

**Issue by IRHM** [DNYLA/Labmaker#14]
Currently the bot asks the member questions one after another, which isn't a great user experience and a lot of people don't fully understand how to reply and why the bot is asking them questions.

We can replace the current process with a Ticket Creation Form on possibly the site that is to be the Tutor site.

**New process to create a ticket:**
- User clicks link to go to ticket creation form.
- They sign in with discord so they can see all their tickets later on and edit the active ones if they need to.
- When they submit the form, the bot will create the ticket channel, send an embed into it with the ticket info and notify tutors. Could optionally PM the user to tell them a ticket has been created in the server.

**Comment by graveship** [comment]
Implemented on Alpha Branch. Once User Dashboard is finished & tested it will be merged to the main branch.
